Fix wrong hash calculation for annotated tags

diff --git a/test/test_submoduletag b/test/test_submoduletag
--- a/test/test_submoduletag
+++ b/test/test_submoduletag
@@ -77,28 +77,36 @@ assert "--skip-existing skips if submodule tag hash is same" <<'EOF'
   then exit 0; else printf "ERROR output:\n%s" "$x";exit 1; fi
 EOF
 
-git tag -f tag_lw  # move the lightweight tag to current commit to test ...
+git tag -f tag_ann # move the annotated tag to current commit to test ...
 # ... renaming/skipping of existing tags
 
 assert "--skip-existing fails if submodule tag hash is different" <<'EOF'
-  x="$(tag-submodule --skip-existing tag_lw 2>&1 || : )"
-  if [[ $x =~ "Tag 'tag_lw' already exists"  ]]; 
+  x="$(tag-submodule --skip-existing tag_ann 2>&1 || : )"
+  if [[ $x =~ "Tag 'tag_ann' already exists"  ]]; 
   then exit 0; else printf "ERROR output:\n%s" "$x";exit 1; fi
 EOF
 
-# creates tag_lw_2 in child
+# creates tag_ann_2 in child
 assert "--rename-existing renames tag if it exists already" <<'EOF'
-  x="$(tag-submodule --rename-existing tag_lw 2>&1 || : )"
-  if [[ $x =~ "Renaming tag 'tag_lw' to 'tag_lw_2'"  ]]; 
+  x="$(tag-submodule --rename-existing tag_ann 2>&1 || : )"
+  if [[ $x =~ "Renaming tag 'tag_ann' to 'tag_ann_2'"  ]]; 
   then exit 0; else printf "ERROR output:\n%s" "$x";exit 1; fi
 EOF
 
 assert "--rename-existing --skip-existing skips renamed tag if it exists already" <<'EOF'
-  x="$(tag-submodule --rename-existing tag_lw 2>&1 || : )"
-  if [[ $x =~ Skipping.*tag_lw.*already\ exists.*tag_lw_2  ]]; 
+  x="$(tag-submodule --rename-existing tag_ann 2>&1 || : )"
+  if [[ $x =~ Skipping.*tag_ann.*already\ exists.*tag_ann_2  ]]; 
   then exit 0; else printf "ERROR output:\n%s" "$x";exit 1; fi
 EOF
 
+exit 1 
+
+assert "When repeating --rename-existing --skip-existing, new new tags are created" <<'EOF'
+  # Requires test "--rename-existing --skip-existing skips renamed tag if it exists already" to have just run
+  x="$(tag-submodule --rename-existing --skip-existing tag_ann 2>&1 || : )"
+  if [[ ! $x =~ "Renaming tag 'tag_ann'"  ]]; 
+  then exit 0; else printf "ERROR output:\n%s" "$x";exit 1; fi
+EOF
 # Tear down
 cd "$thisdir"
 rm -rf parent01 gpg
